// Generated by gencpp from file robot_custom_msgs/db.msg
// DO NOT EDIT!


#ifndef ROBOT_CUSTOM_MSGS_MESSAGE_DB_H
#define ROBOT_CUSTOM_MSGS_MESSAGE_DB_H

#include <ros/service_traits.h>


#include <robot_custom_msgs/dbRequest.h>
#include <robot_custom_msgs/dbResponse.h>


namespace robot_custom_msgs
{

struct db
{

typedef dbRequest Request;
typedef dbResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct db
} // namespace robot_custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_custom_msgs::db > {
  static const char* value()
  {
    return "0b56db4429947d5d82235b9718d8f033";
  }

  static const char* value(const ::robot_custom_msgs::db&) { return value(); }
};

template<>
struct DataType< ::robot_custom_msgs::db > {
  static const char* value()
  {
    return "robot_custom_msgs/db";
  }

  static const char* value(const ::robot_custom_msgs::db&) { return value(); }
};


// service_traits::MD5Sum< ::robot_custom_msgs::dbRequest> should match
// service_traits::MD5Sum< ::robot_custom_msgs::db >
template<>
struct MD5Sum< ::robot_custom_msgs::dbRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_custom_msgs::db >::value();
  }
  static const char* value(const ::robot_custom_msgs::dbRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_custom_msgs::dbRequest> should match
// service_traits::DataType< ::robot_custom_msgs::db >
template<>
struct DataType< ::robot_custom_msgs::dbRequest>
{
  static const char* value()
  {
    return DataType< ::robot_custom_msgs::db >::value();
  }
  static const char* value(const ::robot_custom_msgs::dbRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_custom_msgs::dbResponse> should match
// service_traits::MD5Sum< ::robot_custom_msgs::db >
template<>
struct MD5Sum< ::robot_custom_msgs::dbResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_custom_msgs::db >::value();
  }
  static const char* value(const ::robot_custom_msgs::dbResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_custom_msgs::dbResponse> should match
// service_traits::DataType< ::robot_custom_msgs::db >
template<>
struct DataType< ::robot_custom_msgs::dbResponse>
{
  static const char* value()
  {
    return DataType< ::robot_custom_msgs::db >::value();
  }
  static const char* value(const ::robot_custom_msgs::dbResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_CUSTOM_MSGS_MESSAGE_DB_H
