// Generated by gencpp from file robot_custom_msgs/dbRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_CUSTOM_MSGS_MESSAGE_DBREQUEST_H
#define ROBOT_CUSTOM_MSGS_MESSAGE_DBREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_custom_msgs
{
template <class ContainerAllocator>
struct dbRequest_
{
  typedef dbRequest_<ContainerAllocator> Type;

  dbRequest_()
    : id(0)  {
    }
  dbRequest_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef int64_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::robot_custom_msgs::dbRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_custom_msgs::dbRequest_<ContainerAllocator> const> ConstPtr;

}; // struct dbRequest_

typedef ::robot_custom_msgs::dbRequest_<std::allocator<void> > dbRequest;

typedef boost::shared_ptr< ::robot_custom_msgs::dbRequest > dbRequestPtr;
typedef boost::shared_ptr< ::robot_custom_msgs::dbRequest const> dbRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_custom_msgs::dbRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_custom_msgs::dbRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_custom_msgs::dbRequest_<ContainerAllocator1> & lhs, const ::robot_custom_msgs::dbRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_custom_msgs::dbRequest_<ContainerAllocator1> & lhs, const ::robot_custom_msgs::dbRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_custom_msgs::dbRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_custom_msgs::dbRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_custom_msgs::dbRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_custom_msgs::dbRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_custom_msgs::dbRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_custom_msgs::dbRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_custom_msgs::dbRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef7df1d34137d3879d089ad803388efa";
  }

  static const char* value(const ::robot_custom_msgs::dbRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef7df1d34137d387ULL;
  static const uint64_t static_value2 = 0x9d089ad803388efaULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_custom_msgs::dbRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_custom_msgs/dbRequest";
  }

  static const char* value(const ::robot_custom_msgs::dbRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_custom_msgs::dbRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#inputs\n"
"int64 id\n"
"\n"
;
  }

  static const char* value(const ::robot_custom_msgs::dbRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_custom_msgs::dbRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dbRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_custom_msgs::dbRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_custom_msgs::dbRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CUSTOM_MSGS_MESSAGE_DBREQUEST_H
