// Generated by gencpp from file robot_custom_msgs/OrderDataRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_CUSTOM_MSGS_MESSAGE_ORDERDATAREQUEST_H
#define ROBOT_CUSTOM_MSGS_MESSAGE_ORDERDATAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_custom_msgs
{
template <class ContainerAllocator>
struct OrderDataRequest_
{
  typedef OrderDataRequest_<ContainerAllocator> Type;

  OrderDataRequest_()
    : start()  {
    }
  OrderDataRequest_(const ContainerAllocator& _alloc)
    : start(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _start_type;
  _start_type start;





  typedef boost::shared_ptr< ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct OrderDataRequest_

typedef ::robot_custom_msgs::OrderDataRequest_<std::allocator<void> > OrderDataRequest;

typedef boost::shared_ptr< ::robot_custom_msgs::OrderDataRequest > OrderDataRequestPtr;
typedef boost::shared_ptr< ::robot_custom_msgs::OrderDataRequest const> OrderDataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator1> & lhs, const ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator1> & lhs, const ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34ede85548daeef03201b4a532fb98e1";
  }

  static const char* value(const ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34ede85548daeef0ULL;
  static const uint64_t static_value2 = 0x3201b4a532fb98e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_custom_msgs/OrderDataRequest";
  }

  static const char* value(const ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#inputs\n"
"string start\n"
"\n"
;
  }

  static const char* value(const ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OrderDataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_custom_msgs::OrderDataRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CUSTOM_MSGS_MESSAGE_ORDERDATAREQUEST_H
