# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_custom_msgs/dbRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class dbRequest(genpy.Message):
  _md5sum = "ef7df1d34137d3879d089ad803388efa"
  _type = "robot_custom_msgs/dbRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#inputs
int64 id

"""
  __slots__ = ['id']
  _slot_types = ['int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(dbRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
    else:
      self.id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.id
      buff.write(_get_struct_q().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 8
      (self.id,) = _get_struct_q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.id
      buff.write(_get_struct_q().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 8
      (self.id,) = _get_struct_q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_q = None
def _get_struct_q():
    global _struct_q
    if _struct_q is None:
        _struct_q = struct.Struct("<q")
    return _struct_q
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_custom_msgs/dbResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class dbResponse(genpy.Message):
  _md5sum = "d43bda5143fd7d192dd6191338cdba5e"
  _type = "robot_custom_msgs/dbResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#output
int64 tableid

float64 target_pick_position_x
float64 target_pick_position_y
float64 target_pick_position_z

float64 target_pick_orientation_x
float64 target_pick_orientation_y
float64 target_pick_orientation_z
float64 target_pick_orientation_w

float64 target_place_position_x
float64 target_place_position_y
float64 target_place_position_z

float64 target_place_orientation_x
float64 target_place_orientation_y
float64 target_place_orientation_z
float64 target_place_orientation_w

string text



"""
  __slots__ = ['tableid','target_pick_position_x','target_pick_position_y','target_pick_position_z','target_pick_orientation_x','target_pick_orientation_y','target_pick_orientation_z','target_pick_orientation_w','target_place_position_x','target_place_position_y','target_place_position_z','target_place_orientation_x','target_place_orientation_y','target_place_orientation_z','target_place_orientation_w','text']
  _slot_types = ['int64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       tableid,target_pick_position_x,target_pick_position_y,target_pick_position_z,target_pick_orientation_x,target_pick_orientation_y,target_pick_orientation_z,target_pick_orientation_w,target_place_position_x,target_place_position_y,target_place_position_z,target_place_orientation_x,target_place_orientation_y,target_place_orientation_z,target_place_orientation_w,text

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(dbResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.tableid is None:
        self.tableid = 0
      if self.target_pick_position_x is None:
        self.target_pick_position_x = 0.
      if self.target_pick_position_y is None:
        self.target_pick_position_y = 0.
      if self.target_pick_position_z is None:
        self.target_pick_position_z = 0.
      if self.target_pick_orientation_x is None:
        self.target_pick_orientation_x = 0.
      if self.target_pick_orientation_y is None:
        self.target_pick_orientation_y = 0.
      if self.target_pick_orientation_z is None:
        self.target_pick_orientation_z = 0.
      if self.target_pick_orientation_w is None:
        self.target_pick_orientation_w = 0.
      if self.target_place_position_x is None:
        self.target_place_position_x = 0.
      if self.target_place_position_y is None:
        self.target_place_position_y = 0.
      if self.target_place_position_z is None:
        self.target_place_position_z = 0.
      if self.target_place_orientation_x is None:
        self.target_place_orientation_x = 0.
      if self.target_place_orientation_y is None:
        self.target_place_orientation_y = 0.
      if self.target_place_orientation_z is None:
        self.target_place_orientation_z = 0.
      if self.target_place_orientation_w is None:
        self.target_place_orientation_w = 0.
      if self.text is None:
        self.text = ''
    else:
      self.tableid = 0
      self.target_pick_position_x = 0.
      self.target_pick_position_y = 0.
      self.target_pick_position_z = 0.
      self.target_pick_orientation_x = 0.
      self.target_pick_orientation_y = 0.
      self.target_pick_orientation_z = 0.
      self.target_pick_orientation_w = 0.
      self.target_place_position_x = 0.
      self.target_place_position_y = 0.
      self.target_place_position_z = 0.
      self.target_place_orientation_x = 0.
      self.target_place_orientation_y = 0.
      self.target_place_orientation_z = 0.
      self.target_place_orientation_w = 0.
      self.text = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_q14d().pack(_x.tableid, _x.target_pick_position_x, _x.target_pick_position_y, _x.target_pick_position_z, _x.target_pick_orientation_x, _x.target_pick_orientation_y, _x.target_pick_orientation_z, _x.target_pick_orientation_w, _x.target_place_position_x, _x.target_place_position_y, _x.target_place_position_z, _x.target_place_orientation_x, _x.target_place_orientation_y, _x.target_place_orientation_z, _x.target_place_orientation_w))
      _x = self.text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 120
      (_x.tableid, _x.target_pick_position_x, _x.target_pick_position_y, _x.target_pick_position_z, _x.target_pick_orientation_x, _x.target_pick_orientation_y, _x.target_pick_orientation_z, _x.target_pick_orientation_w, _x.target_place_position_x, _x.target_place_position_y, _x.target_place_position_z, _x.target_place_orientation_x, _x.target_place_orientation_y, _x.target_place_orientation_z, _x.target_place_orientation_w,) = _get_struct_q14d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.text = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_q14d().pack(_x.tableid, _x.target_pick_position_x, _x.target_pick_position_y, _x.target_pick_position_z, _x.target_pick_orientation_x, _x.target_pick_orientation_y, _x.target_pick_orientation_z, _x.target_pick_orientation_w, _x.target_place_position_x, _x.target_place_position_y, _x.target_place_position_z, _x.target_place_orientation_x, _x.target_place_orientation_y, _x.target_place_orientation_z, _x.target_place_orientation_w))
      _x = self.text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 120
      (_x.tableid, _x.target_pick_position_x, _x.target_pick_position_y, _x.target_pick_position_z, _x.target_pick_orientation_x, _x.target_pick_orientation_y, _x.target_pick_orientation_z, _x.target_pick_orientation_w, _x.target_place_position_x, _x.target_place_position_y, _x.target_place_position_z, _x.target_place_orientation_x, _x.target_place_orientation_y, _x.target_place_orientation_z, _x.target_place_orientation_w,) = _get_struct_q14d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.text = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_q14d = None
def _get_struct_q14d():
    global _struct_q14d
    if _struct_q14d is None:
        _struct_q14d = struct.Struct("<q14d")
    return _struct_q14d
class db(object):
  _type          = 'robot_custom_msgs/db'
  _md5sum = '0b56db4429947d5d82235b9718d8f033'
  _request_class  = dbRequest
  _response_class = dbResponse
