#inputs
int64 id

---
#output
int64 tableid

float64 target_pick_position_x
float64 target_pick_position_y
float64 target_pick_position_z

float64 target_pick_orientation_x
float64 target_pick_orientation_y
float64 target_pick_orientation_z
float64 target_pick_orientation_w

float64 target_place_position_x
float64 target_place_position_y
float64 target_place_position_z

float64 target_place_orientation_x
float64 target_place_orientation_y
float64 target_place_orientation_z
float64 target_place_orientation_w

string text


